export const PATHS = {
  metadata: ".codeforge/metadata.json",
  config: ".codeforge/config.yaml",
  rootEnv: ".env",
  codeforgeEnv: ".codeforge/.env",
  intentsDir: ".codeforge/intents",
  plansDir: ".codeforge/plans",
  tasksDir: ".codeforge/tasks",
  executionsDir: ".codeforge/executions",
  rulesDir: ".codeforge/rules",
  docsDir: ".codeforge/docs",
  docsManifest: ".codeforge/docs/manifest.json",
  planningRules: ".codeforge/rules/planning.md",
  runningRules: ".codeforge/rules/running.md",
  docsRules: ".codeforge/rules/docs.md",
  docsUpdateRules: ".codeforge/rules/docs-update.md",
  intentFile: (name: string) => `.codeforge/intents/${name}.md`,
  taskFile: (intent: string, id: string) => `.codeforge/tasks/${intent}/${id}.json`,
  executionState: (intent: string) => `.codeforge/executions/${intent}.json`,
} as const;
