import { NodeWorkspaceGateway } from "../../../infrastructure/workspace.js";
import { Command } from "commander";
import { select } from "@inquirer/prompts";
import { validatePlan } from "../../../application/validate.js";
import { getAvailableSpecs } from "../../../application/plan.js";

export function registerPlanValidateCommand(plan: Command): void {
  plan
    .command("validate [spec] [taskId]")
    .description("Validate the JSON tasks generated by the AI agent")
    .action(async (spec?: string, taskId?: string) => {
      const gw = new NodeWorkspaceGateway(process.cwd());
      let specName = spec;

      if (!specName) {
        const specs = getAvailableSpecs(gw);

        if (specs.length === 0) {
          console.error("\n✗ No specs found.\n");
          process.exitCode = 1;
          return;
        }

        specName = await select({
          message: "Select a spec to validate its plan:",
          choices: specs.map((s) => ({ name: s, value: s })),
        });
      }

      const result = validatePlan(gw, specName, taskId);

      switch (result.kind) {
        case "not-initialized":
          console.error(
            "\n✗ CodeForge is not initialized. Run `codeforge init` first.\n",
          );
          process.exitCode = 1;
          break;
        case "spec-not-found":
          console.error(`\n✗ No tasks directory found for spec: ${specName}\n`);
          process.exitCode = 1;
          break;
        case "invalid":
          console.error(`\n✗ Validation failed for plan '${specName}':\n`);
          for (const err of result.errors) {
            console.error(`  - ${err}`);
          }
          console.error(
            "\n[AI INSTRUCTION] Fix these errors in the JSON files and run validation again.\n",
          );
          process.exitCode = 1;
          break;
        case "valid":
          console.log(
            `\n✓ Plan for '${specName}' is valid and ready for execution!\n`,
          );
          break;
      }
    });
}
