import { NodeWorkspaceGateway } from "../../../infrastructure/workspace.js";
import { Command } from "commander";
import { select } from "@inquirer/prompts";
import { validatePlan } from "../../../application/validate.js";
import { getAvailableSpecs } from "../../../application/plan.js";
import { translate } from "../../ui/i18n.js";
import { ConfigService } from "../../../config/ConfigService.js";

export function registerPlanValidateCommand(plan: Command): void {
  plan
    .command("validate [spec] [taskId]")
    .description("Validate the JSON tasks generated by the AI agent")
    .action(async (spec?: string, taskId?: string) => {
      const gw = new NodeWorkspaceGateway(process.cwd());
      
      const configService = new ConfigService(gw);
      const config = configService.loadConfig();
      const lang = config?.language || "en";

      let specName = spec;

      if (!specName) {
        const specs = getAvailableSpecs(gw);

        if (specs.length === 0) {
          console.error(translate("err_no_specs_run", lang));
          process.exitCode = 1;
          return;
        }

        specName = await select({
          message: translate("validate_select_spec", lang),
          choices: [
            { name: translate("menu_back", lang), value: "back" },
            ...specs.map((s) => ({ name: s, value: s }))
          ],
        });

        if (specName === "back") {
          if (process.env.CODEFORGE_INTERACTIVE) {
            process.exit(200);
          } else {
            process.exit(0);
          }
        }
      }

      const result = validatePlan(gw, specName, taskId);

      switch (result.kind) {
        case "not-initialized":
          console.error(translate("err_not_initialized", lang));
          process.exitCode = 1;
          break;
        case "spec-not-found":
          console.error(translate("err_tasks_dir_not_found", lang, { spec: specName }));
          process.exitCode = 1;
          break;
        case "invalid":
          console.error(translate("plan_err_validation_failed", lang, { spec: specName }));
          for (const err of result.errors) {
            console.error(`  - ${err}`);
          }
          console.error(translate("plan_err_fix_instructions", lang));
          process.exitCode = 1;
          break;
        case "valid":
          console.log(translate("validate_success", lang, { spec: specName }));
          break;
      }
    });
}
